Repository octokit/request.js, pull requests merged in 2020-05, with the labels that each got.

#127 fix(README): typo in authentication section
  README.md
Labels: bug, documentation

#130 Replace Greenkeeper with Dependabot
  .github/dependabot.yml
  .github/workflows/test.yml
  .github/workflows/update-prettier.yml
  README.md
Labels: maintenance

#141 fix(deps): pin typescript version due to #137
  package.json
Labels: bug
