Repository octokit/request.js, pull requests merged in 2022-07, with the labels that each got.

#481 refactor: failover from native fetch to node-fetch
  src/fetch-wrapper.ts
Labels: feature

#488 docs(readme): use native `fetch` API first
  README.md
Labels: bug, documentation

#483 ci(test): use test_matrix and test jobs
  .github/workflows/test.yml
Labels: maintenance

#489 [deps] updates pika/pack to a non vulnerable version
  package-lock.json
  package.json
Labels: dependencies, maintenance

#442 feat: special handling for `AbortError`
  README.md
  src/fetch-wrapper.ts
  test/request.test.ts
Labels: feature
