Repository octokit/request.js, pull requests merged in 2023-07, with the labels that each got.

#599 feat: v8
  README.md
  package-lock.json
  package.json
  src/fetch-wrapper.ts
  test/request.test.ts
Labels: Type: Feature, Type: Breaking change

#604 fix: remove data argument
  src/fetch-wrapper.ts
Labels: Type: Maintenance

#608 docs(readme): use 'user-agent' instead of 'agent' as 'header' option in 'Sentible defauls' section
  README.md
Labels: Type: Documentation

#610 fix: correct the passing of the `signal` option
  src/fetch-wrapper.ts
Labels: Type: Bug

#612 fix(types): remove `redirect` option
  src/fetch-wrapper.ts
Labels: Type: Bug

#614 docs(readme): add example for using a custom Agent
  README.md
Labels: Type: Documentation

#602 feat: add parseSuccessResponseBody Option
  README.md
  package-lock.json
  package.json
  src/fetch-wrapper.ts
  test/request.test.ts
Labels: Type: Feature

#617 fix(fetch-wrapper): improve error message when 'fetch' implementation is not present
  src/fetch-wrapper.ts
  test/request.test.ts
Labels: Type: Maintenance

#619 Add auto responder workflow
  .github/workflows/immediate-response.yml
Labels: Type: Maintenance
