Repository octokit/request.js, pull requests merged in 2023-05, with the labels that each got.

#584 fix(build): replace pika with esbuild and tsc
  package-lock.json
  package.json
  scripts/build.mjs
  test/request.test.ts
  tsconfig.json
Labels: Type: Maintenance, Priority: High

#581 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
Labels: Type: Maintenance, Type: Breaking change

#580 BREAKING CHANGE: remove `node-fetch` in favor of global
  README.md
  package-lock.json
  package.json
  src/fetch-wrapper.ts
  src/get-buffer-response.ts
  test/request.test.ts
Labels: Type: Feature, Type: Breaking change
