Repository octokit/request.js, pull requests merged in 2024-02, with the labels that each got.

#676 test: remove `AbortController` and `AbortSignal` polyfills
  test/request.test.ts
Labels: Type: Maintenance

#678 feat: switch to ESM output
  README.md
  package-lock.json
  package.json
  scripts/build.mjs
  src/fetch-wrapper.ts
  test/request.test.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Feature, Type: Breaking change

#609 docs(readme): examples use ESM
  README.md
Labels: Type: Documentation

#681 fix(pkg): add `main` export
  scripts/build.mjs
Labels: Type: Bug
